// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A flow for suggesting maintenance schedules based on vehicle
 *   information and reported issues.
 *
 * - suggestMaintenanceSchedule - A function that suggests a maintenance schedule
 *   for a vehicle.
 * - SuggestMaintenanceScheduleInput - The input type for the
 *   suggestMaintenanceSchedule function.
 * - SuggestMaintenanceScheduleOutput - The return type for the
 *   suggestMaintenanceSchedule function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestMaintenanceScheduleInputSchema = z.object({
  make: z.string().describe('The make of the vehicle.'),
  model: z.string().describe('The model of the vehicle.'),
  year: z.number().describe('The year of the vehicle.'),
  mileage: z.number().describe('The current mileage of the vehicle.'),
  reportedIssues: z
    .string()
    .describe('Any issues reported by the user about the vehicle.'),
});
export type SuggestMaintenanceScheduleInput = z.infer<
  typeof SuggestMaintenanceScheduleInputSchema
>;

const SuggestMaintenanceScheduleOutputSchema = z.object({
  maintenanceSchedule: z
    .string()
    .describe(
      'A detailed maintenance schedule based on the vehicle information and reported issues.'
    ),
});
export type SuggestMaintenanceScheduleOutput = z.infer<
  typeof SuggestMaintenanceScheduleOutputSchema
>;

export async function suggestMaintenanceSchedule(
  input: SuggestMaintenanceScheduleInput
): Promise<SuggestMaintenanceScheduleOutput> {
  return suggestMaintenanceScheduleFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestMaintenanceSchedulePrompt',
  input: {schema: SuggestMaintenanceScheduleInputSchema},
  output: {schema: SuggestMaintenanceScheduleOutputSchema},
  prompt: `You are an expert mechanic that will provide an optimal maintenance schedule for a vehicle based on its make, model, year, mileage, and any reported issues.

  Vehicle Make: {{{make}}}
  Vehicle Model: {{{model}}}
  Vehicle Year: {{{year}}}
  Vehicle Mileage: {{{mileage}}}
  Reported Issues: {{{reportedIssues}}}

  Please provide a detailed maintenance schedule, including:
  - Regular maintenance tasks (e.g., oil change, filter replacements)
  - Recommended inspection intervals
  - Potential repairs based on reported issues
  - Estimated timelines for each task
  - Any additional notes or considerations.
  The response should be formatted in markdown.
  `,
});

const suggestMaintenanceScheduleFlow = ai.defineFlow(
  {
    name: 'suggestMaintenanceScheduleFlow',
    inputSchema: SuggestMaintenanceScheduleInputSchema,
    outputSchema: SuggestMaintenanceScheduleOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
